### ISSUE TITLE
design package to-do list

### ISSUE THREAD

**Issue by jwnigel** [jwnigel/permaculture#6]
- [ ] After dragging and dropping trees to the screen, upon resizing the window the trees move dynamically with the RelativeLayout. However, they do not move correctly with the background image! In order to keep the image proportions, padding is added to the top/bottom or sides of the image as the window is resized. I think one solution to this would be to [crop the image](https://stackoverflow.com/questions/57763591/how-can-i-crop-images-according-to-the-window-size?newreg=ec59bf4231644722aafe797a1df36327) instead of padding it. 
- [ ] When I click on the tree icon (IconButton class) it creates a DraggableImage in the MapLayout directly over the button's location. However you have to click on this again to drag it. Need to set it's default drag state to True somehow. I already tried using on_motion property. 
- [ ] Resize the tree (DraggableImage) drag size. Right now the size is set to the size of tree IconButton, which is a vertical rectangle. I had no luck with the size or texture_size so will try changing its drag_rectangle properties. Can skip this for now as I think it wont matter when the tree size is set correctly to the map size. 
- [ ] Create database (using SQLite3 for now?) and start playing with selecting a few from dropdown menus.

**Comment by berteh** [comment]
- [ ] add layers that would allow to draw structure elements (new paths, buildings, keyholes, ponds...) on top of background pic/grid, under vegetation design layer.
